name: auto_check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  test_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install deps
      - name: Install deps
        run: npm i

      # Run linter
      - name: Lint
        run: npm run lint

      # Run formatter
      - name: Format
        run: npm run format

      # Run tests
      - name: Tests
        run: npm test

      # Run build
      - name: Build
        run: npm run build

      # Run Stryker-Mutator check
      # - name: Stryker-Mutator
      #   run: npm run test:mutate
      #
