name: stryker-test

on:
  workflow_dispatch:

jobs:
  test_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install deps
      - name: Install deps
        run: npm i

      # Run Stryker-Mutator check
      - name: Stryker-Mutator
        run: npm run test:mutate
